spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ADDRESS}:3306/gonggang?autoReconnect=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB